### ISSUE TITLE
save intermediate outputs to a branch dedicated to the issue

### ISSUE THREAD

**Issue by dmarx** [irgolic/AutoPR#36]
Job was killed due to a rate limiting error: https://github.com/dmarx/autopr-keyframed/actions/runs/4623506281/jobs/8177383098

looks like the requested information had completed generation and the error was thrown during a validation step. would be nice if the job could pick up where it left off. you could create a PR after the first generation completes and then iteratively update the intermediate outputs on the PR's branch. scratchpad notes and other planning outputs could potentially be saved as comments on the PR or even the triggering issue.

**Comment by irgolic** [comment]
I've been thinking about this, and I think this would create more problems than it would solve.

The error thrown in the issue was a rate limit error, which we handle much better now. It's sad when an error like that gets in the way, but when I rerun PR generation it's usually because of a semantic error – in which case I would like it to start from a clean slate. In an ideal UX, you would be able to rerun from a specific previous point in the process, but I don't see a neat way of doing that on Github. Rather, let's focus on improving upon previous runs in #31.

If you disagree, please reopen the issue.

**Comment by Konard** [comment]
@irgolic use PR comments instead for intermediate data. Make it real conversation.
